#!/usr/bin/env python3
"""Extract the PR material physics table into terrain_params.json (task 2.7).

Reads material/materialmanagerdefine.con from raw_game_data/common_server.zip
(read-only, in-memory) and rewrites ONLY the "materials" section of
processor/terrain_params.json; all other sections are hand-authored config and
are preserved semantically (the file is re-serialized, so formatting may
change). Re-runnable. Extraction is all-or-nothing: any incomplete material
block aborts the run WITHOUT touching the existing config, and the config is
replaced atomically (temp sibling + os.replace) so an interrupted run cannot
leave a truncated file.

The file is auto-generated by PRMaterials: blocks separated by blank lines, each
starting with `Material.active <id>` followed by `Material.name "X"`,
`Material.friction`, `Material.resistance`, and optional flags such as
`Material.hasWaterPhysics 1`.
"""
import json
import os
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZIP_PATH = ROOT / "raw_game_data" / "common_server.zip"
MEMBER = "material/materialmanagerdefine.con"
CONFIG_PATH = Path(__file__).resolve().parent / "terrain_params.json"

ACTIVE_RE = re.compile(r"^Material\.active\s+(\d+)", re.I)
PROP_RE = re.compile(r"^Material\.(\S+)\s*(.*)$", re.I)
PROVENANCE = "extracted from v1.9 files, speed effect unverified"


def parse_materials(text):
    """Parse PRMaterials blocks into a list of material dicts."""
    entries = []
    current = None
    for line in text.splitlines():
        line = line.strip()
        active = ACTIVE_RE.match(line)
        if active:
            current = {"id": int(active.group(1))}
            entries.append(current)
            continue
        if current is None:
            continue
        prop = PROP_RE.match(line)
        if not prop:
            continue
        key, value = prop.group(1).lower(), prop.group(2).strip()
        if key == "name":
            current["name"] = value.strip('"')
        elif key in ("friction", "resistance", "elasticity"):
            current[key] = float(value)
        elif key == "haswaterphysics":
            current["has_water_physics"] = bool(int(value))
    return entries


REQUIRED_FIELDS = ("id", "name", "friction", "resistance")


def validate_materials(entries):
    """All-or-nothing validation; raises ValueError before any config write.

    A truncated or malformed source must never replace a good material table
    (review finding S1-F01). Every entry needs the physics fields this table
    exists to record, and ids must be unique."""
    if not entries:
        raise ValueError("no materials parsed")
    ids = set()
    for index, entry in enumerate(entries):
        missing = [field for field in REQUIRED_FIELDS if field not in entry]
        if missing:
            raise ValueError(
                "material block %d (id=%s) missing fields: %s"
                % (index, entry.get("id", "?"), ", ".join(missing)))
        if entry["id"] in ids:
            raise ValueError("duplicate material id %s" % entry["id"])
        ids.add(entry["id"])


def main():
    if not ZIP_PATH.exists():
        print("ERROR: expected input not found:", ZIP_PATH)
        print("Place the maintainer-provided common_server.zip under raw_game_data/.")
        return 1
    with zipfile.ZipFile(ZIP_PATH) as archive:
        text = archive.read(MEMBER).decode("ascii", errors="replace")
    entries = parse_materials(text)
    try:
        validate_materials(entries)
    except ValueError as error:
        print("ERROR: extraction rejected, config NOT modified:", error)
        return 1
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    config["materials"] = {"provenance": PROVENANCE, "entries": entries}
    serialized = json.dumps(config, indent=2) + "\n"
    temporary = CONFIG_PATH.with_suffix(".json.tmp")
    temporary.write_text(serialized, encoding="ascii")
    os.replace(temporary, CONFIG_PATH)
    named = sum(1 for entry in entries if entry.get("name"))
    water = sum(1 for entry in entries if entry.get("has_water_physics"))
    print("materials=%d named=%d water_physics=%d -> %s"
          % (len(entries), named, water, CONFIG_PATH.name))
    for entry in entries:
        if entry.get("name") in ("Tarmac", "Dirt", "Sand", "Gravel", "Grass"):
            print("  id=%(id)s %(name)s friction=%(friction)s resistance=%(resistance)s" % entry)
    return 0


if __name__ == "__main__":
    sys.exit(main())
